// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/prisma/schema",
  migrations: {
    path: "src/prisma/migrations",
    seed: 'npm run seed',
  },
  datasource: {
    url: `mysql://${process.env["DATABASE_USER"]}:${process.env["DATABASE_PASSWORD"]}@${process.env["DATABASE_HOST"]}:${process.env["DATABASE_PORT"] || 3306}/${process.env["DATABASE_NAME"]}`,
    shadowDatabaseUrl: `mysql://${process.env["DATABASE_USER"]}:${process.env["DATABASE_PASSWORD"]}@${process.env["DATABASE_HOST"]}:${process.env["DATABASE_PORT"] || 3306}/${process.env["DATABASE_NAME"]}_shadow`,
  },
});
